apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    name: postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamodb
  labels:
    name: dynamodb
---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticmq
  labels:
    name: elasticmq
---
apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    name: application