apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: application
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      #securityContext:
      #  runAsUser: 70
      #  runAsGroup: 70
      #  fsGroup: 70
      containers:
      - name: auth-service
        image: 076892642827.dkr.ecr.us-east-1.amazonaws.com/toggle-master/auth-service:1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        #  readOnlyRootFilesystem: false
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 9
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: auth-service-database-url-secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: auth-service-configmap
        - name: MASTER_KEY
          valueFrom:
            secretKeyRef:
              key: MASTER_KEY
              name: auth-service-master-key-secret
      restartPolicy: Always
