apiVersion: v1
kind: Secret
metadata:
  name: auth-service-database-url-secret
  namespace: application
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hdXRoX3NlcnZpY2U6YXV0aF9zZXJ2aWNlQDIwMjZAZGF0YWJhc2UtZGV2LTAxLmNueW4ycmQybG91dC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9hdXRoX2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-master-key-secret
  namespace: application
type: Opaque
data:
  MASTER_KEY: YWRtaW4ta2V5QDIwMjY=