FROM postgres:17-alpine

# Set default environment variables (Override these at runtime)
ENV POSTGRES_USER=flag_service
ENV POSTGRES_PASSWORD=flag_service@2026
ENV POSTGRES_DB=flags_db

# Expose the default PostgreSQL port
EXPOSE 5432