apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-database-url-secret
  namespace: application
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly90YXJnZXRpbmdfc2VydmljZTp0YXJnZXRpbmdfc2VydmljZTIwMjZAdGFyZ2V0aW5nLXNlcnZpY2UtZGItc3ZjLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvdGFyZ2V0aW5nX2Ri