apiVersion: v1
kind: Secret
metadata:
  name: flag-service-database-url-secret
  namespace: application
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9mbGFnX3NlcnZpY2U6ZmxhZ19zZXJ2aWNlMjAyNkBkYXRhYmFzZS1kZXYtMDIuY255bjJyZDJsb3V0LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdzX2Ri