apiVersion: v1
kind: Service
metadata:
  name: flag-service-svc
  namespace: application
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002