apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-configmap
  namespace: application
data:
  AUTH_SERVICE_URL: "http://auth-service-svc.application.svc.cluster.local:8001"
  PORT: "8003"