apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-database-url-secret
  namespace: application
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly90YXJnZXRpbmdfc2VydmljZTp0YXJnZXRpbmdfc2VydmljZTIwMjZAZGF0YWJhc2UtZGV2LTAzLmNueW4ycmQybG91dC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi90YXJnZXRpbmdfZGI=