name: flag-service
namespace: application
port: 8002
replicas: 1
resources:
  limits:
    cpu: "200m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
image:
  repository: 076892642827.dkr.ecr.us-east-1.amazonaws.com/toggle-master
  name: flag-service
  tag: "v1.0.0-98f4c97fe833930a2deec4e721caac6141508e63-DEV"
  pullPolicy: IfNotPresent
configmap:
  AUTH_SERVICE_URL: "http://auth-service-svc.application.svc.cluster.local:8001"
  PORT: "8002"
secrets:
  DATABASE_URL: cG9zdGdyZXM6Ly9mbGFnX3NlcnZpY2U6ZmxhZ19zZXJ2aWNlMjAyNkBkYXRhYmFzZS1kZXYtMDIuY255bjJyZDJsb3V0LnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdzX2Ri
probes:
  startup:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 9
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
service:
  type: ClusterIP
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  averageCpuUtilization: 10
  averageMemoryUtilization: 10
keda:
  enabled: false
  type: ""
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 10
  queueLength: ""
  awsRegion: "us-east-1"
  queueURL: ""
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsSessionToken: ""
