apiVersion: v1
kind: Secret
metadata:
  name: auth-service-database-url-secret
  namespace: application
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9hdXRoX3NlcnZpY2U6YXV0aF9zZXJ2aWNlQDIwMjZAYXV0aC1zZXJ2aWNlLWRiLXN2Yy5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2F1dGhfZGI=
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-master-key-secret
  namespace: application
type: Opaque
data:
  MASTER_KEY: YWRtaW4ta2V5QDIwMjY=