apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-configmap
  namespace: application
data:
  REDIS_URL: "redis://redis-0.redis-svc.redis.svc.cluster.local:6379"
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service-svc.application.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service-svc.application.svc.cluster.local:8003"
  AWS_SQS_URL: "http://elasticmq-svc.elasticmq.svc.cluster.local:9324/000000000000/queue-toggle-master"
  AWS_SQS_ENDPOINT: "http://elasticmq-svc.elasticmq.svc.cluster.local:9324"
  AWS_REGION: "us-east-1"