apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-api-key-secret
  namespace: application
type: Opaque
data:
  SERVICE_API_KEY: dG1fa2V5XzY3OTY3ZWRhMjQzZDhkMzYzNTFlNGVhZmU2YzJlZTM0ZWExNDM2NWZhMzAzNjc1MzE1ODE1NjkxNDU0NjA5MjQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-aws-secret
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9jYWw=
  AWS_SECRET_ACCESS_KEY: bG9jYWw=