apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        startupProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.probes.startupInitialDelaySeconds }}
          periodSeconds: {{ .Values.probes.startupPeriodSeconds }}
          failureThreshold: {{ .Values.probes.startupFailureThreshold }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.probes.livenessInitialDelaySeconds }}
          periodSeconds: {{ .Values.probes.livenessPeriodSeconds }}
          failureThreshold: {{ .Values.probes.livenessFailureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.port }}
          initialDelaySeconds: {{ .Values.probes.readinessInitialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readinessPeriodSeconds }}
          failureThreshold: {{ .Values.probes.readinessFailureThreshold }}
        ports:
        - containerPort: {{ .Values.port }}
        env:
        {{- range $key, $value := .Values.configmap }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              key: {{ $key }}
              name: {{ $.Values.name }}-configmap
        {{- end }}
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              key: {{ $key }}
              name: {{ $.Values.name }}-secrets
        {{- end }}
      restartPolicy: Always
