FROM postgres:17-alpine

# Set default environment variables (Override these at runtime)
ENV POSTGRES_USER=auth_service
ENV POSTGRES_PASSWORD=auth_service@2026
ENV POSTGRES_DB=auth_db

# Expose the default PostgreSQL port
EXPOSE 5432