apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-configmap
  namespace: application
data:
  PORT: "8004"
  FLAG_SERVICE_URL: "http://flag-service-svc.application.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service-svc.application.svc.cluster.local:8003"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/076892642827/queue-toggle-master"
  AWS_SQS_ENDPOINT: "https://sqs.us-east-1.amazonaws.com"
  AWS_REGION: "us-east-1"