name: analytics-service
namespace: application
port: 8005
replicas: 1
resources:
  limits:
    cpu: "200m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"
image:
  repository: 598450975126.dkr.ecr.us-east-1.amazonaws.com
  name: analytics-service
  tag: "v1.0.0-e949ab92c96f44b2affecb53d246336f1a0de04d-DEV"
  pullPolicy: IfNotPresent
configmap:
  PORT: "8005"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/598450975126/queue-toggle-master"
  AWS_SQS_ENDPOINT: "https://sqs.us-east-1.amazonaws.com"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_DYNAMODB_ENDPOINT: "https://dynamodb.us-east-1.amazonaws.com"
  AWS_REGION: "us-east-1"
secrets:
  AWS_ACCESS_KEY_ID: QVNJQVlXVlRWR0dMTENXM1BJREM=
  AWS_SECRET_ACCESS_KEY: UnNKcnk0c0NuNmREeWdhaGFVTmRVOHZwakFaWGlIT1RqZFBvK3lsRA==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVQTC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRDRLQnVxdHJyWjR3dWNvOVlVai9pUDFRNUwwQnh2UVRQNk4wY0hab3kwQ2dJaEFOYkNBTEMxNVFENklTYzZ0cXN6SVlRNElFVFdXWnRoNTJlVGwydlpVYm1BS3NFQ0NMdi8vLy8vLy8vLy93RVFBUm9NTlRrNE5EVXdPVGMxTVRJMklneWdyVmR1T1FubktReklLZDRxbFFJYkxJZGVlUE1VdllHQklBeHYrMWdGYjBLRE1WcWlFM0R3YmxVYURFVHRyQzIwblRLYlZNRmY1VUY5eFNqck4vNjkvYXdmVGROV1JXc1B0WEpMV2NYWWpSU3k4TlQ3T1ZPbE01Q3E2aHBEOERGSHJRY2hZQUtuQzdOUStHbCtPZDVBMjhNOFNjNXNYSk1Yb3hDQ3pkYUhtM1NUaWN5VjluN1phUWZxOHc5b1hDeDFGaFU3TFdLMStqVmR3S0ZlV2hnN3FYM0poY25vaWxPaVZqeENhcjJJRXhML2Y0Q2g0SUxURDlPVnphQVJrNzBqQnF1S0Q2NnFUR1BuZ0lmRzZoWFZlTkRDODJFNTBYNStndkoxQlRiQ3dCVlh2bzJ6cWJSTnpEWWgrU1pXdUo5K0xIRVpvV3JyZUxRNXVveEl5bFk0TnhPV3RjRTR2V0EwZThMSFdxWUtOSVJmVjVVSzNKc2oyUlR1Z3ZUaVczQy8xenE0TVBPa2x0VUdPcHdCR2FpajVob3hDRVV1S3UyUzRvUzFvT25nYmQ1YXpmd3dWYTVPMWRKdkRobkNUSjJSTnVwYlV4U1FocnVrdG1LSUpOaXlxc2xEbmhhY2lUSHY1V1VrUXJnRFFRRloySDBQam5DdmZiakh4Skw5bDlSbW9RK2grUkY4aTQyeWJIUVFraXRGdkRzY0FJcGRzUWJQN1NJeHA5UzJGWG5HTzcxMUMvQmtLcXN0ZTlmWGdRRWthMDdXVVVrTXQybit4aGVsMHRGdTVjZzdUKzNSR1pWRA==
probes:
  startup:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
    failureThreshold: 9
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
service:
  type: ClusterIP
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  averageCpuUtilization: 90
  averageMemoryUtilization: 90
keda:
  enabled: true
  type: aws-sqs-queue
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod: 30
  pollingInterval: 10
  queueLength: "5"
  awsRegion: "us-east-1"
  queueURL: "queue-toggle-master"
  awsAccessKeyId: QVNJQVlXVlRWR0dMTENXM1BJREM=
  awsSecretAccessKey: UnNKcnk0c0NuNmREeWdhaGFVTmRVOHZwakFaWGlIT1RqZFBvK3lsRA==
  awsSessionToken: SVFvSmIzSnBaMmx1WDJWakVQTC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpJTUVZQ0lRRDRLQnVxdHJyWjR3dWNvOVlVai9pUDFRNUwwQnh2UVRQNk4wY0hab3kwQ2dJaEFOYkNBTEMxNVFENklTYzZ0cXN6SVlRNElFVFdXWnRoNTJlVGwydlpVYm1BS3NFQ0NMdi8vLy8vLy8vLy93RVFBUm9NTlRrNE5EVXdPVGMxTVRJMklneWdyVmR1T1FubktReklLZDRxbFFJYkxJZGVlUE1VdllHQklBeHYrMWdGYjBLRE1WcWlFM0R3YmxVYURFVHRyQzIwblRLYlZNRmY1VUY5eFNqck4vNjkvYXdmVGROV1JXc1B0WEpMV2NYWWpSU3k4TlQ3T1ZPbE01Q3E2aHBEOERGSHJRY2hZQUtuQzdOUStHbCtPZDVBMjhNOFNjNXNYSk1Yb3hDQ3pkYUhtM1NUaWN5VjluN1phUWZxOHc5b1hDeDFGaFU3TFdLMStqVmR3S0ZlV2hnN3FYM0poY25vaWlPaVZqeENhcjJJRXhML2Y0Q2g0SUxURDlPVnphQVJrNzBqQnF1S0Q2NnFUR1BuZ0lmRzZoWFZlTkRDODJFNTBYNStndkoxQlRiQ3dCVlh2bzJ6cWJSTnpEWWgrU1pXdUo5K0xIRVpvV3JyZUxRNXVveEl5bFk0TnhPV3RjRTR2V0EwZThMSFdxWUtOSVJmVjVVSzNKc2oyUlR1Z3ZUaVczQy8xenE0TVBPa2x0VUdPcHdCR2FpajVob3hDRVV1S3UyUzRvUzFvT25nYmQ1YXpmd3dWYTVPMWRKdkRobkNUSjJSTnVwYlV4U1FocnVrdG1LSUpOaXlxc2xEbmhhY2lUSHY1V1VrUXJnRFFRRloySDBQam5DdmZiakh4Skw5bDlSbW9RK2grUkY4aTQyeWJIUVFraXRGdkRzY0FJcGRzUWJQN1NJeHA5UzJGWG5HTzcxMUMvQmtLcXN0ZTlmWGdRRWthMDdXVVVrTXQybit4aGVsMHRGdTVjZzdUKzNSR1pWRA==
